[package]
name = "arkaive"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
directories = "5.0"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
shellexpand = "3.1.0"
tar = "0.4.40"
toml = "0.8.13"
